name-singular: gnugus
name-plural: gnugi
format-singular: '%n gnugus'
format-plural: '%n gnugi'
allow-creative: false
currency-family: gold
text-balance: '&3You have &6%g&3.'
text-balance-perms-fail: '&6You cannot use item currency at this time.'
custom-currency: {}