name-singular: gnugus
name-plural: gnugi
format-singular: '%n gnugus'
format-plural: '%n gnugi'
allow-creative: false
currency-family: gold
text-balance: '&3You have &6%g&3.'
text-balance-perms-fail: '&6You cannot use item currency at this time.'
text-reloaded: '&3GoldIsMoney has reloaded.'
text-admin-perms-fail: '&6You do not have admin privs for GoldIsMoney.'
fractional-digits: 0
custom-currency: {}
allow-fake-players: true
allow-banks: true